### PR TITLE
Get rid of several warnings

### PR DESCRIPTION
**Pull request by Lonami**

### CODE REVIEW

**Comment by Lonami** [comment]
I'm bored. Considering this is meant to be a library, I feel like the generated types should be public if we want other people to access them at all. Right?

**Review by JuanPotato — COMMENTED** [review]
I mean, there's no need to change it to +. crc32 strings are at most 8 chars. So if anything you'd want to turn it in to `{,8}` for compliance.

**Comment by Lonami** [comment]
Fair, although `{,8}` would allow for the possibility of 0 characters which is invalid.

**Comment by JuanPotato** [comment]
Finally pushed code, was working on stuff before this, id advise against opening anything for now since I'm likely to be renovating a ton of stuff

**Pull request closed without merging**
